// Curated backend fixtures (docs/ARCHITECTURE_PLAN.md step 4, item 7) and the
// MSW handlers that serve them, in Jest and behind the Playwright server.
//
// The "normal" JSON files are real backend responses, generated by
// scripts/generate-fixtures.py from the backend's route code (except
// basketball.team.json; see its _note). Scenarios are derived here, chosen by
// the conference in the path or by ?season=:
//
//   any conference          normal
//   "Empty"                 { data: [] }: a conference with no teams
//   "Missing_Fields"        rows keep only team_name and team_id
//   "Preseason"             every record 0-0, no distributions
//   ?season=<archived>      normal rows, conferences marked "(archive)"
//
// Endpoints without a fixture answer 404, so pages still show their error
// states for everything else.

import { http, HttpResponse, type HttpHandler } from "msw";
import { ENDPOINTS, type EndpointKey } from "../../src/api/endpoints";
import basketballStandings from "./basketball.standings.json";
import basketballTeam from "./basketball.team.json";
import basketballTeams from "./basketball.teams.json";
import footballStandings from "./football.standings.json";
import footballTeam from "./football.team.json";
import footballTeams from "./football.teams.json";

type Json = Record<string, unknown>;
type Row = Record<string, unknown>;

export const FIXTURES: Partial<Record<EndpointKey, Json>> = {
  "basketball.standings": basketballStandings,
  "basketball.team": basketballTeam,
  "basketball.teams": basketballTeams,
  "football.standings": footballStandings,
  "football.team": footballTeam,
  "football.teams": footballTeams,
};

export type Scenario = "normal" | "empty" | "missingFields" | "preseason" | "archived";

export const SCENARIO_CONFERENCES: Record<Exclude<Scenario, "normal" | "archived">, string> = {
  empty: "Empty",
  missingFields: "Missing_Fields",
  preseason: "Preseason",
};

function scenarioFor(params: Record<string, string>, season: string | null): Scenario {
  const conference = (params.conference ?? "").replace(/ /g, "_");
  for (const [scenario, name] of Object.entries(SCENARIO_CONFERENCES)) {
    if (conference === name) return scenario as Scenario;
  }
  return season ? "archived" : "normal";
}

function mapRows(body: Json, change: (row: Row) => Row): Json {
  return Array.isArray(body.data) ? { ...body, data: (body.data as Row[]).map(change) } : body;
}

const RECORD = /record$/;

/** A fixture body for an endpoint in a scenario, or undefined if none. */
export function fixtureFor(key: EndpointKey, scenario: Scenario): Json | undefined {
  const body = FIXTURES[key];
  if (!body) return undefined;
  switch (scenario) {
    case "normal":
      return body;
    case "empty":
      return Array.isArray(body.data) ? { ...body, data: [] } : body;
    case "missingFields":
      return mapRows(body, (row) => ({ team_name: row.team_name, team_id: row.team_id }));
    case "preseason":
      return mapRows(body, (row) =>
        Object.fromEntries(
          Object.entries(row).map(([k, v]) => [
            k,
            RECORD.test(k) ? "0-0" : typeof v === "number" ? 0 : v && typeof v === "object" && !Array.isArray(v) ? {} : v,
          ]),
        ),
      );
    case "archived":
      return {
        ...body,
        ...(Array.isArray(body.conferences) && {
          conferences: (body.conferences as string[]).map((c) => `${c} (archive)`),
        }),
      };
  }
}

// MSW path pattern for an endpoint path ("/football/standings/:conference").
const pattern = (path: string) => path.replace(/^\/?/, "/");

/** Requests the handlers have answered, newest last (for Playwright tests). */
export const requestLog: string[] = [];

function handlersFor(base: string, pathOf: (key: EndpointKey) => string[]): HttpHandler[] {
  return ENDPOINTS.filter((e) => e.method === "GET" && FIXTURES[e.key as EndpointKey]).flatMap(
    (endpoint) =>
      pathOf(endpoint.key as EndpointKey).map((path) =>
        http.get(`${base}${pattern(path)}`, ({ request, params }) => {
          const url = new URL(request.url);
          requestLog.push(`${url.pathname}${url.search}`);
          const scenario = scenarioFor(
            params as Record<string, string>,
            url.searchParams.get("season"),
          );
          const body = fixtureFor(endpoint.key as EndpointKey, scenario);
          return body
            ? HttpResponse.json(body)
            : HttpResponse.json({ error: "No fixture" }, { status: 404 });
        }),
      ),
  );
}

/**
 * Handlers for the Flask backend's URLs under `baseUrl` (what the proxy and
 * server-api fetch), e.g. "http://fixtures.test/api".
 */
export function backendHandlers(baseUrl: string): HttpHandler[] {
  const byKey = new Map(ENDPOINTS.map((e) => [e.key, e]));
  return [
    ...handlersFor(baseUrl, (key) => [byKey.get(key)!.backendPath]),
    // Anything else the backend would serve: no fixture.
    http.all(`${baseUrl}/*`, ({ request }) => {
      requestLog.push(new URL(request.url).pathname);
      return HttpResponse.json({ error: "No fixture" }, { status: 404 });
    }),
  ];
}

/** Handlers for the site's own proxy URLs (what browser code fetches). */
export function proxyHandlers(origin: string): HttpHandler[] {
  const byKey = new Map(ENDPOINTS.map((e) => [e.key, e]));
  return handlersFor(`${origin}/api/proxy`, (key) =>
    byKey.get(key)!.proxyPaths.map((p) => `/${p}/`),
  );
}
